### ISSUE TITLE
MemoryPool destroy problem

### ISSUE THREAD

**Issue by shaochenguang** [cacay/MemoryPool#7]
hello There's a question I'd like to ask.
template <typename T, size_t BlockSize>
MemoryPool<T, BlockSize>::~MemoryPool()
noexcept
{
  slot_pointer_ curr = currentBlock_;
  while (curr != nullptr) {
    slot_pointer_ prev = curr->next;
    operator delete(reinterpret_cast<void*>(curr));
    curr = prev;
  }
}

currentBlock_ is not operator new(BlockSize) return address. If there are multiple blocks, MemoryPool destroy Unable to release memory. 
I think we need to add a linked list record operator new(BlockSize) address

**Comment by Duum** [comment]
```
  data_pointer_ newBlock = reinterpret_cast<data_pointer_>
                           (operator new(BlockSize));
  reinterpret_cast<slot_pointer_>(newBlock)->next = currentBlock_;
currentBlock_ = reinterpret_cast<slot_pointer_>(newBlock);
```
I don't understand your problem. i think the currentBlock is just the operator new(BlockSize) address

**Comment by shaochenguang** [comment]
oh sorry， I write one less member . You're right.
